# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c81b379b1a56433c444b31dd2bd23f8294edafb8b2fba85abfc10ed374ef69a6c2610a91407b805f64344f1b23159f65639d3630a9712483de66af2612a84e67

test:
  secret_key_base: b1ecfb81bfc80fd40426ef72ed825bec6f80d3f3643c1073367c6bbaad7cd637b1058d72cee490bf980e7e6a48ebc9f5765fec90904138297702884255975f83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
