# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


elizabeth = User.create({name: "Rotten Tooth '94", email: "elizabeth@gmail.com", password: "password", admin_code: "FocusVitaminWaterXXX"})
marco = User.create({name: "Marcoa", email: "marcoa@gmail.com", password: "password", admin_code: "FocusVitaminWaterXXX"})
walter = User.create({name: "Walter", email: "walter@gmail.com", password: "password", admin_code: "plz make me an admin"})

drama = Category.create({name: "Drama"})
action = Category.create({name: "Action"})
comedy = Category.create({name: "Comedy"})
thriller = Category.create({name: "Thriller"})
horror = Category.create({name: "Horror"})
adventure = Category.create({name: "Adventure"})
romance = Category.create({name: "Romance"})
documentary = Category.create({name: "Documentary"})

drama.films << Film.new({title: "Star Wars Ep. I", director: "George Lucas", summary: "Drama in space", year: "1960"})
drama.films << Film.new({title: "Star Wars Ep. II", director: "George Lucas", summary: "Another drama in space", year: "1961"})
drama.films << Film.new({title: "Mini Marco", director: "George lopez", summary: "Another drama in DBC", year: "1994"})
drama.films << Film.new({title: "HUGE Marco", director: "George Lucas", summary: "Another drama in DBC", year: "1994"})
drama.films << Film.new({title: "Always One Step Ahead", director: "George Lucas", summary: "Marco was born one day before Elizabeth", year: "1961"})
drama.films << Film.new({title: "Walter's name backwards is Retlaw", director: "Angelina Jolie", summary: "The more you know", year: "1961"})
action.films << Film.new({title: "Star Wars Ep. III", director: "George Lucas", summary: "Action in space", year: "1962"})
action.films << Film.new({title: "9 Fast 10 Furious", director: "Uber", summary: "Action with cars", year: "2017"})
action.films << Film.new({title: "Schema Design", director: "Sam Quell Lorem", summary: "Do you get the director's name??? It's pretty clever", year: "1962"})
action.films << Film.new({title: "Ringing the Bell", director: "George Lucas", summary: "Getting jobs", year: "1962"})
comedy.films << Film.new({title: "Star Wars Ep. V", director: "George L", summary: "Comedy in space", year: "1965"})
comedy.films << Film.new({title: "Star Wars Ep. IV", director: "George L", summary: "Comedy in space the revange", year: "1966"})
comedy.films << Film.new({title: "We are Farmers", director: "Marco", summary: "Because we are SEEDing data. GET IT", year: "1966"})
comedy.films << Film.new({title: "Roommate's Birthday", director: "George L", summary: "Gotta get her some presents", year: "1966"})
comedy.films << Film.new({title: "Uh", director: "George L", summary: "Walter needs to say more things", year: "1966"})
thriller.films << Film.new({title: "The revenge", director: "Marco Martinez", summary: "Comming back to get you", year: "1967"})
thriller.films << Film.new({title: "The revenge 2", director: "Marco Martinez", summary: "Comming back to get you again", year: "1967"})
thriller.films << Film.new({title: "The revenge 3", director: "Marco Martinez", summary: "Comming back to get you again again", year: "1967"})
thriller.films << Film.new({title: "The revenge 4: Return of the Revenge", director: "Marco Martinez", summary: "Comming back to get you even more", year: "1967"})
horror.films << Film.new({title: "Rotten Tooth", director: "Niko", summary: "Inside the mouth", year: "1968"})
horror.films << Film.new({title: "Internity", director: "Myra", summary: "Hahaha?", year: "1968"})
horror.films << Film.new({title: "Uneven Spacing", director: "Elizabeth", summary: "My code looks so so awful", year: "1968"})
horror.films << Film.new({title: "React", director: "Everyone", summary: "Why not use rails?", year: "1968"})
horror.films << Film.new({title: "Dominant in a group of Steadies", director: "Myra", summary: "Help I'm a dominant personality type and I'm such an awful person in this group. Please tell me if you want to type!!!!", year: "1968"})
adventure.films << Film.new({title: "Star Wars Ep. 10", director: "George Lopez", summary: "George lopez goes to space.", year: "1967"})
adventure.films << Film.new({title: "Music Festival", director: "EDM", summary: "Pretty sure Randall's Island used to be an asylum? Overdose!", year: "1967"})
adventure.films << Film.new({title: "Sorry Not Sorry", director: "Marco", summary: "Good bye final project.", year: "1967"})
adventure.films << Film.new({title: "Starbucks Run", director: "Team Motivated", summary: "Is it awkward that everyone else is working and we're just eating? I feel like we're still getting things done. But I also feel like we are bad people.", year: "1967"})
romance.films << Film.new({title: "Scarlett Johansson meets Marco", director: "Micheal Jackson and kids", summary: "Based on a true love events", year: "2016"})
romance.films << Film.new({title: "Emma Watson meets Walter", director: "Harry Potter", summary: "Based on a true love events", year: "2016"})
romance.films << Film.new({title: "Channing Tatum meets Elizabeth", director: "Channing Tatum", summary: "Based on a true love events", year: "2016"})
romance.films << Film.new({title: "Mila Kunis meets Marco", director: "Ashton Kutcher", summary: "Based on a true love events", year: "2016"})
romance.films << Film.new({title: "Megan Fox meets Walter", director: "Shia LeBeoff", summary: "Based on a true love events", year: "2016"})
romance.films << Film.new({title: "Chris Hemsworth meets Elizabeth", director: "The Avengers", summary: "Based on a true love events", year: "2016"})
documentary.films << Film.new({title: "DBC", director: "Pan", summary: "...", year: "1969"})
documentary.films << Film.new({title: "Elizabeth is Hilarious", director: "Elizabeth", summary: "This is really true", year: "2016"})
documentary.films << Film.new({title: "Elizabeth meets Chris Hemsworth", director: "Real Life", summary: "This is really true. Actually though.", year: "2016"})
documentary.films << Film.new({title: "Elizabeth Makes Documentaries About Herself", director: "Real Life", summary: "This is really true. Actually though.", year: "2016"})


drama.films.first.reviews << Review.new({user_id: 1, content: "It was meh", star_rating: 3})
drama.films.first.reviews << Review.new({user_id: 2, content: "Yeah I mean no, I mean yeah, I mean no. I mean, I dunno", star_rating: 9})
comedy.films.first.reviews << Review.new({user_id: 2, content: "It was pretty funny. I laughed.", star_rating: 4})
comedy.films.first.reviews << Review.new({user_id: 1, content: "I didn't really laugh. Could have been funnier", star_rating: 2})

drama.films.last.votes << Vote.new({user_id: 1})
drama.films.last.votes << Vote.new({user_id: 2})
drama.films.last.votes << Vote.new({user_id: 3})

drama.films.first.reviews.first.votes << Vote.new({user_id: 2})
drama.films.first.reviews.first.votes << Vote.new({user_id: 3})

comedy.films.first.reviews.first.comments << Comment.new({body: "This was a wack review. I agree.", user_id: 3})
comedy.films.first.reviews.first.comments.first.votes << Vote.new({user_id: 1})

comedy.films.first.comments << Comment.new({body: "This was a great movie. I agree.", user_id: 2})
comedy.films.first.comments << Comment.new({body: "Awesome movie", user_id: 2})
drama.films.first.comments << Comment.new({body: "It was okay.", user_id: 2})
horror.films.first.comments << Comment.new({body: "It was to scary.", user_id: 1})
documentary.films.first.comments << Comment.new({body: "Fall asleep.", user_id: 2})
